# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


# Docs:
# Docker Task Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops&preserve-view=true
# This yaml file is from this guide: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/acr-template?view=azure-devops
# Docker on Windows Install: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'rcconsertestakscr-con'
  imageRepository: 'mydocimage1'
  #containerRegistry: 'rcconsertestakscr'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'
  agent_pool: 'aks_agent_pool_linux'



stages:

- stage: ACRLogin
  displayName: ACRLogin
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(agent_pool)
    steps:
    #- task: PowerShell@2 #Verify that the user running these commands is the Network Service user
    #  inputs:
    #    targetType: inline
    #    script: whoami
    - task: Bash@3
      inputs:
        targetType: inline
        script: whoami
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)


- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(agent_pool)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

